#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

productName: "eric-oss-notification-service"
productNumber: "CXD 101 0769"
images:
  ns:
    productName: "Notification Service"
    productNumber: "CXU 101 0710"
    registry: "armdocker.rnd.ericsson.se"
    repoPath: REPO_PATH
    name: IMAGE_NAME
    tag: VERSION
