/*******************************************************************************
 * COPYRIGHT Ericsson 2020
 *
 *
 *
 * The copyright to the computer program(s) herein is the property of
 *
 * Ericsson Inc. The programs may be used and/or copied only with written
 *
 * permission from Ericsson Inc. or in accordance with the terms and
 *
 * conditions stipulated in the agreement/contract under which the
 *
 * program(s) have been supplied.
 ******************************************************************************/

package com.ericsson.oss.common.service.ns.filter;

public class FilterBase {

  public String getSimpleEvent() {
    return "{ \"a\": \"a-value\", \"b\": \"b-value\", \"c\": 2, \"d\": { \"a\": 2.0, \"b\": [1, 2, 3]}, \"e\": [\"a\", \"b\"], \"f\": true }";
  }

  public String getSimpleEvent2() {
    return "[{ \"a\": \"a-value\", \"b\": \"b-value\", \"c\": 2, \"d\": { \"a\": 2.0, \"b\": [1, 2, 3]}, \"e\": [\"a\", \"b\"], \"f\": true },"
            + "{ \"a\": \"a2-value\", \"b\": \"b2-value\", \"c\": 3, \"d\": { \"a\": 4.0, \"b\": [4, 5]}, \"e\": [\"c\", \"d\", \"e\"], \"f\": false }]";
  }
  
  public String getServiceOrderCreateEvent() {
    return "{ \n"
            + "    \"eventId\": \"00001\", \n"
            + "    \"eventTime\": \"2015-11-16T16:42:25-04:00\", \n"
            + "    \"eventType\": \"ServiceOrderCreateEvent\", \n"
            + "    \"event\": { \n"
            + "        \"serviceOrder\": \n"
            + "                { \n"
            + "                    \"id\": \"42\", \n"
            + "                    \"href\": \"http://serverlocation:port/serviceOrdering/v4/serviceOrder/42\", \n"
            + "                    \"externalId\": \"BSS747\", \n"
            + "                    \"priority\": \"1\", \n"
            + "                    \"description\": \"Service order description\", \n"
            + "                    \"category\": \"TMF resource illustration\", \n"
            + "                    \"state\": \"acknowledged\", \n"
            + "                    \"orderDate\": \"2018-01-12T09:37:40.508Z\", \n"
            + "                    \"completionDate\": \"\", \n"
            + "                    \"requestedStartDate\": \"2018-01-15T09:37:40.508Z\", \n"
            + "                    \"requestedCompletionDate\": \"2018-01-15T09:37:40.508Z\", \n"
            + "                    \"expectedCompletionDate\": \"2018-01-15T09:37:40.508Z\", \n"
            + "                    \"startDate\": \"2018-01-12T09:37:40.508Z\", \n"
            + "                    \"@type\": \"ServiceOrder\", \n"
            + "                    \"note\": [ \n"
            + "                        { \n"
            + "                            \"date\": \"2018-01-15T09:37:40.508Z\", \n"
            + "                            \"author\": \"Harvey Poupon\", \n"
            + "                            \"text\": \"Some text\" \n"
            + "                        } \n"
            + "                    ], \n"
            + "                    \"relatedParty\": [ \n"
            + "                        { \n"
            + "                            \"id\": \"456\", \n"
            + "                            \"href\": \"http://serverlocation:port/partyManagement/v4/party/456\", \n"
            + "                            \"role\": \"requester\", \n"
            + "                            \"name\": \"Jean Pontus\", \n"
            + "                            \"@referredType\": \"Individual\" \n"
            + "                        } \n"
            + "                    ], \n"
            + "                    \"serviceOrderItem\": [ \n"
            + "                        { \n"
            + "                            \"id\": \"1\", \n"
            + "                            \"action\": \"add\", \n"
            + "                            \"state\": \"acknowledged\", \n"
            + "                            \"service\": { \n"
            + "                                \"@type\": \"Service\", \n"
            + "                                \"name\": \"sample service1\", \n"
            + "                                \"serviceType\": \"RFS\", \n"
            + "                                \"serviceCharacteristic\": [ \n"
            + "                                    { \n"
            + "                                        \"name\": \"bandwidth\", \n"
            + "                                        \"valueType\": \"String\", \n"
            + "                                        \"value\": \"100Mbps\" \n"
            + "                                    }, \n"
            + "                                    { \n"
            + "                                        \"name\": \"subsystemName\", \n"
            + "                                        \"valueType\": \"String\", \n"
            + "                                        \"value\": \"ecm\" \n"
            + "                                    }         \n"
            + "                                ], \n"
            + "                                \"serviceSpecification\": { \n"
            + "                                    \"id\": \"90ce2704-6366-469b-8373-ce0671c9c845\",\n"
            + "                                    \"name\": \"TMF_ServiceTemplate\",\n"
            + "                                    \"version\": \"1\"               \n"
            + "                                }             \n"
            + "                            }           \n"
            + "                        },\n"
            + "                        { \n"
            + "                            \"id\": \"2\", \n"
            + "                            \"action\": \"add\", \n"
            + "                            \"state\": \"acknowledged\", \n"
            + "                            \"service\": { \n"
            + "                                \"@type\": \"Service\", \n"
            + "                                \"name\": \"sample service1\", \n"
            + "                                \"serviceType\": \"RFS\", \n"
            + "                                \"serviceCharacteristic\": [ \n"
            + "                                    { \n"
            + "                                        \"name\": \"bandwidth\", \n"
            + "                                        \"valueType\": \"String\", \n"
            + "                                        \"value\": \"200Mbps\" \n"
            + "                                    }, \n"
            + "                                    { \n"
            + "                                        \"name\": \"subsystemName\", \n"
            + "                                        \"valueType\": \"String\", \n"
            + "                                        \"value\": \"ecm\" \n"
            + "                                    }         \n"
            + "                                ], \n"
            + "                                \"serviceSpecification\": { \n"
            + "                                    \"id\": \"90ce2704-6366-469b-8373-ce0671c9c846\",\n"
            + "                                    \"name\": \"TMF_ServiceTemplate\",\n"
            + "                                    \"version\": \"1\"               \n"
            + "                                }             \n"
            + "                            }           \n"
            + "                        }\n"
            + "                    ]\n"
            + "                }\n"
            + "    }\n"
            + "}";
  }

  public String getTroubleTicketStateChangeNotification() {
    return "{\n"
            + "  \"eventId\": \"00001\",\n"
            + "  \"eventTime\": \"2015-11-16T16:42:25-04:00\",\n"
            + "  \"eventType\": \"TroubleTicketStateChangeNotification\",\n"
            + "  \"event\": {\n"
            + "    \"troubleTicket\":\n"
            + "            {\n"
            + "              \"id\": \"43\",\n"
            + "              \"href\": \" /troubleTicketManagement/troubleTicket/43\",\n"
            + "              \"correlationId\": \"TT53483\",\n"
            + "              \"description\": \"Customer complaint over last invoice.\",\n"
            + "              \"severity\": \"Urgent\",\n"
            + "              \"@type\": \"TroubleTicket\",\n"
            + "              \"creationDate\": \"2013-07-23T08:16:39.0Z\",\n"
            + "              \"targetResolutionDate\": \"2013-07-30T10:20:01.0Z\",\n"
            + "              \"status\": \"In Progress\",\n"
            + "              \"statusChangeReason\": \"Waiting for invoicing expert.\",\n"
            + "              \"statusChangeDate\": \"2013-07-24T08:55:12.0Z\",\n"
            + "              \"relatedParty\": [{\n"
            + "                  \"href\": \" /customerManagement/customer/1234\",\n"
            + "                  \"role\": \"Originator\"\n"
            + "                },\n"
            + "                {\n"
            + "                  \"href\": \" /partyManagement/individual/1234\",\n"
            + "                  \"role\": \"Owner\"\n"
            + "                },\n"
            + "                {\n"
            + "                  \"href\": \" /partyManagement/individual/2334\",\n"
            + "                  \"role\": \"Reviser\"\n"
            + "                }\n"
            + "              ],\n"
            + "              \"relatedObject\": [{\n"
            + "                  \"involvement\": \"Disputed\",\n"
            + "                  \"reference\": \" https:server:port/billManagement/customerBill/1234\"\n"
            + "                },\n"
            + "                {\n"
            + "                  \"involvement\": \"Adjusted\",\n"
            + "                  \"reference\": \" https:server:port/billManagement/customerBill/5678\"\n"
            + "                }\n"
            + "              ],\n"
            + "              \"note\": [{\n"
            + "                  \"date\": \"2013-07-24T09:55:30.0Z\",\n"
            + "                  \"author\": \"Arthur Evans\",\n"
            + "                  \"text\": \"Already called the expert\"\n"
            + "                },\n"
            + "                {\n"
            + "                  \"date\": \"2013-07-25T08:55:12.0Z\",\n"
            + "                  \"author\": \"Arthur Evans\",\n"
            + "                  \"text\": \"Informed the originator\"\n"
            + "                }\n"
            + "              ]\n"
            + "            }\n"
            + "  }\n"
            + "}\n"
            + "";
  }

  public String getAlarm() {
    return "{\n"
            + "  \"@type\": \"event\",\n"
            + "  \"@schemaLocation\": \"http://xx/Event.schema.json\",\n"
            + "  \"@baseType\": \"event\",\n"
            + "  \"eventId\": \"256c42f0-7cae-4cfe-8b96-f5773796f8ff\",\n"
            + "  \"eventTime\": \"2019-11-02T14:20:54\",\n"
            + "  \"eventType\": \"AlarmCreateNotification\",\n"
            + "  \"correlationId\": \"238764827364827t367\",\n"
            + "  \"domain\": \"domain-x\",\n"
            + "  \"title\": \"Mail service not responding\",\n"
            + "  \"description\": \"The mail service is no longer responding and sending mails\",\n"
            + "  \"timeOccurred\": \"2019-11-02T14:20:54\",\n"
            + "  \"timeReceived\": \"2019-11-02T14:21:08\",\n"
            + "  \"priority\": \"Normal\",\n"
            + "  \"source\": {\n"
            + "    \"id\": \"12345\",\n"
            + "    \"href\": \".../relatedEntity/12345\"\n"
            + "  },\n"
            + "  \"reportingSystem\": {\n"
            + "    \"id\": \"34534\",\n"
            + "    \"href\": \"/reportingEntity/12345\",\n"
            + "    \"name\": \"name\"\n"
            + "  },\n"
            + "  \"relatedParty\": [\n"
            + "    {\n"
            + "      \"id\": \"12312\",\n"
            + "      \"href\": \"/party/12345\",\n"
            + "      \"role\": \"Owner\"\n"
            + "    }\n"
            + "  ],\n"
            + "  \"event\": {\n"
            + "    \"alarm\": {\n"
            + "      \"@type\": \"alarm\",\n"
            + "      \"@schemaLocation\": \"http://../registry/Alarm.schema.json\",\n"
            + "      \"@baseType\": \"alarm\",\n"
            + "      \"id\": \"ROUTER_IF@Cisco-7609-6-4-4-4-14-14-4--Gi9/20@42\",\n"
            + "      \"href\": \"http://api/alarm/ROUTER_IF@Cisco-7609-6-4-4-4-14-14-4--Gi9/20@42\",\n"
            + "      \"externalAlarmId\": \"cisco-7609-1937465789\",\n"
            + "      \"alarmType\": \"QualityOfServiceAlarm\",\n"
            + "      \"perceivedSeverity\": \"CRITICAL\",\n"
            + "      \"probableCause\": \"Threshold crossed\",\n"
            + "      \"specificProblem\": \"Inbound Traffic threshold crossed\"\n"
            + "    }\n"
            + "  }\n"
            + "}";
  }
}
