#
# COPYRIGHT Ericsson 2020
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-oss-notification-service.name" . }}-psp-binding
  labels:
{{ include "eric-oss-notification-service.labels" .| indent 4 }}
  annotations:
{{ include "eric-oss-notification-service.annotations" . | indent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ template "eric-oss-notification-service.privileged.cluster.role.name" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "eric-oss-notification-service.name" . }}-serviceaccount
