#
# COPYRIGHT Ericsson 2020
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-oss-notification-service.name" . }}-serviceaccount
  labels:
{{ include "eric-oss-notification-service.labels" . | indent 4 }}
  annotations:
{{ include "eric-oss-notification-service.annotations" . | indent 4 }}
---
{{- $global := fromJson (include "eric-oss-notification-service.global" .) -}}
{{- $securityPoliciesDefined := include "eric-oss-notification-service.security-policies-defined" . | trim -}}
{{- if $global.security.policyBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-oss-notification-service.name" . }}-serviceaccount-security-policy
  labels:
{{ include "eric-oss-notification-service.labels" .| nindent 4 }}
  annotations:
{{ include "eric-oss-notification-service.annotations" . | indent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "eric-oss-notification-service.securityPolicy.reference" . }}  
#  name: {{ template "eric-oss-notification-service.release.name" . }}-allowed-use-privileged-policy
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "eric-oss-notification-service.name" . }}-serviceaccount
{{- else if eq $securityPoliciesDefined "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-oss-notification-service.name" . }}-serviceaccount-security-policy
  labels: {{- include "eric-oss-notification-service.labels" . | nindent 4 }}
  annotations:
{{ include "eric-oss-notification-service.annotations" . | indent 4 }}
roleRef:
  kind: {{ .Values.global.securityPolicy.rolekind }}
  name: {{ .Values.securityPolicy.rolename }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "eric-oss-notification-service.name" . }}-serviceaccount
{{- end }}