#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

version: '3.1'
services:
  ns-db:
    image: postgres:10
    user: root
    volumes:
       - ./dbmaster:/docker-entrypoint-initdb.d
       - ./data:/var/lib/postgresql/data
    hostname: ns-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres1#
    ports:
      - "5432:5432"
      
  ns:
    image: armdocker.rnd.ericsson.se/proj-eo/common/proj-notification-service-drop/eric-oss-notification-service:1.0.0-168
    hostname: ns
    depends_on:
      - ns-db
      - kafka1
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=PLAINTEXT://kafka1:9092
      - KAFKA_CONSUMER_AUTO_OFFSET_RESET=latest
      - KAFKA_FETCH_MAX_WAIT=500
      - KAFKA_FETCH_MIN_SIZE=1
      - KAFKA_REPLICATION_FACTOR=1
      - DB_URL=jdbc:postgresql://ns-db:5432/nsdb
      - DB_USER=postgres
      - DB_PASSWORD=Postgres1#
      - JAVA_OPTS=-DREST_READ_TIMEOUT=30000 -DKAFKA_REPLICATION_FACTOR=1 -DKAFKA_CONSUMER_AUTO_OFFSET_RESET=earliest -Dserver.port=8080 -Dspring.profiles.active=external-db -Xdebug -Xrunjdwp:transport=dt_socket,address=*:8001,server=y,suspend=n
    ports:
      - "8080:8080"
      - "8001:8001"

  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./zk-single-kafka-single/zoo1/data:/data
      - ./zk-single-kafka-single/zoo1/datalog:/datalog

  kafka1:
    image: confluentinc/cp-kafka:5.5.1
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:9092 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - ./zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1
